### ISSUE TITLE
add another issue type

### ISSUE THREAD

**Issue by hauschke** [vivo-community/language-ontology#18]
Something like "other" would be good. 

Right now we have only issue types that are directly related to the improvement of the ontology itself.

- Feature request
-- Suggest a term for this ontology
- Improvement request
-- Request an improvement to the ontology

**Comment by mconlon17** [comment]
Done.  I added an "Other" for all other issues.  No prompting.  See https://github.com/vivo-community/language-ontology/commit/7b5a2f64c5b8e30f52642bd06b1039b378c64978
